# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://SwiftLOL.org
repository: SwiftLOL/SwiftLOL.github.io
date_format: "ordinal"
title: 那是一个夏天
subtitle: "SwiftLOL"
description: "王佳佳的个人博客"
keywords: SwiftLOL, Jiajia Wang
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Jiajia Wang
organization: didichuxing, Inc.
organization_url: https://www.didichuxing.com
location: Beijing, China
email: wangjiajiajohn@didichuxing.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: SwiftLOL
douban_username: SwiftLOL
facebook_username: SwiftLOL
weibo_username: SwiftLOL
zhihu_username: SwiftLOL
twitter_username: SwiftLOL

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: SwiftLOL
disqus_username: SwiftLOL
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Objective-c, C++, H5, CSS3]
skill_mobile_app_keywords: [IOS, FE]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
